[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "cascaide"
version = "0.1.0"
description = "Cascaide: Generative Diffusion Model"
requires-python = ">=3.10"

dependencies = [
    "torch",
    "numpy",
    "tqdm",
    "einops",
    "pytest",
    "ovito",
    "hilbertcurve",
    "PyYAML",
    "matplotlib"
]


[tool.setuptools.packages.find]
include = ["cascaide*"]


[tool.pytest.ini_options]
testpaths = ["tests"]