#!/usr/bin/env python
"""Fast cross-model sampling scan with DPM-Solver++(2M), written as a Continuity report page.

Generates n/energy from every local checkpoint with the fast (~20x) DPM-Solver++ sampler and
records the OVERALL + per-energy-REGIME scores into a markdown page. These are FAST, APPROXIMATE
screening numbers (dpmpp ~within-noise of full DDPM at ~30 steps; low-E/high-E regimes less
validated) — NOT verdicts. For definitive scores use full DDPM on the A100 (submit.sh score).

    python scripts/sampling_scan.py --steps 30 --n 16 --out .continuity/sampling-scan.md
"""
import argparse, os, glob, json, hashlib, time
import numpy as np
from cascaide.eval import io, scorecard as scm
from cascaide.eval.generators import generate_set_checkpoint

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGIMES = [("low", 0.0, 50.0), ("mid", 50.0, 150.0), ("high", 150.0, 1e9)]
MIN_REF = 8


def candidates():
    """(path, label, energy_max) for every distinct local set-DiT checkpoint."""
    c = []
    for rj in glob.glob(os.path.join(REPO, "results/runs/*/run.json")):
        mp = os.path.join(os.path.dirname(rj), "model.pt")
        if os.path.exists(mp):
            m = json.load(open(rj)); cfg = (m.get("provenance", {}) or {}).get("config", {}) or {}
            c.append((mp, m.get("label", "?"), cfg.get("energy_max")))
    for r, name in {"r0": "cosine", "r1": "warmup", "r2": "onecycle", "r3": "plateau"}.items():
        p = os.path.join(REPO, f"runs/sweep_7183204.polaris-pbs-01.hsn.cm.polaris.alcf.anl.gov_{r}/best_by_scorecard.pt")
        if os.path.exists(p):
            c.append((p, f"sched-{name}-best7183204", 100.0))
    vg = os.path.join(REPO, "vignesh_model.pt")
    if os.path.exists(vg):
        c.append((vg, "vignesh-global-ep569", None))
    seen, out = set(), []
    for p, label, em in c:
        h = (os.path.getsize(p), hashlib.md5(open(p, "rb").read(4 << 20)).hexdigest()[:10])
        if h in seen:
            continue
        seen.add(h); out.append((p, label, em))
    return out


def regime_scores(gen, ref, ebin):
    out = {}
    for name, lo, hi in REGIMES:
        r = [s for s in ref if lo <= s["energy"] < hi]
        g = [s for s in gen if lo <= s["energy"] < hi]
        out[name] = (scm.compute(g, r, energy_bin=ebin)["score"] if len(r) >= MIN_REF and g else None)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--steps", type=int, default=30)
    ap.add_argument("--n", type=int, default=16)
    ap.add_argument("--energy_bin", type=float, default=25.0)
    ap.add_argument("--device", default="mps")
    ap.add_argument("--out", default=os.path.join(REPO, ".continuity/sampling-scan.md"))
    ap.add_argument("--date", default="")          # pass an absolute date (Date.now unavailable)
    args = ap.parse_args()

    full = io.load_subset(os.path.join(REPO, "data/cascaide_cascades.npz"))
    rows = []
    for p, label, em in candidates():
        ref = [s for s in full if s["energy"] <= em] if em else full
        t0 = time.time()
        gen, _ = generate_set_checkpoint(p, ref, device=args.device, n_per_energy=args.n,
                                         energy_bin=args.energy_bin, steps=args.steps, sampler="dpmpp")
        spc = (time.time() - t0) / max(1, len(gen))
        sc = scm.compute(gen, ref, label=label, energy_bin=args.energy_bin)
        reg = regime_scores(gen, ref, args.energy_bin)
        rows.append({"label": label, "range": "<100" if em else "0-300", "score": sc["score"],
                     "pass": f"{sc['n_requirements_passed']}/{sc['n_requirements']}",
                     "low": reg["low"], "mid": reg["mid"], "high": reg["high"], "spc": spc})
        print(f"[scan] {label[:40]:40s} {sc['score']:.3f}  {spc:.2f}s/cloud", flush=True)

    rows.sort(key=lambda r: r["score"])
    def f(x): return "—" if x is None else f"{x:.3f}"
    lines = [
        "# Sampling scan — DPM-Solver++ (fast inference) across all models", "",
        f"> **Fast, APPROXIMATE screening** via DPM-Solver++(2M) @ {args.steps} steps (~{1000//args.steps}x "
        "fewer forward passes than DDPM-1000), generated locally. **Not verdict-quality** — for "
        "definitive scores use full DDPM-1000 on the A100 (`submit.sh score`).",
        f"> Generated by `scripts/sampling_scan.py` (n={args.n}/energy, {args.device})" + (f", {args.date}." if args.date else "."),
        "",
        "## Method", "",
        f"- **Sampler:** DPM-Solver++(2M), **{args.steps} steps** (vs DDPM-1000), uniform-log-SNR spacing.",
        f"- **n={args.n}** samples/energy; per-energy regime = low `<50` / mid `50–150` / high `>150` keV.",
        "- **Caveats:** dpmpp is within-noise of full DDPM at ~30 steps (n=32 A/B on the 300ep model), but "
        "this scan is single-seed at low n, and the low-E (small-cloud) and full-range high-E regimes are "
        "less validated. Treat as **screening**, not verdicts. See `experiments.md` (fast-sampling finding).",
        "",
        "## Results (overall score, lower = better)", "",
        "| model | train keV | overall | pass | low | mid | high | s/cloud |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| {r['label'][:44]} | {r['range']} | **{r['score']:.3f}** | {r['pass']} | "
                     f"{f(r['low'])} | {f(r['mid'])} | {f(r['high'])} | {r['spc']:.2f} |")
    lines += ["", f"_{len(rows)} checkpoints scanned. Per-regime blanks = no data in that band "
              "(e.g. `<100 keV` models have no high-E regime)._", ""]
    open(args.out, "w").write("\n".join(lines))
    print(f"[scan] wrote {args.out} ({len(rows)} models)", flush=True)


if __name__ == "__main__":
    main()
